# Generated by Django 4.2 on 2023-06-07 11:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "last_modification_date",
                    models.DateTimeField(auto_created=True, blank=True),
                ),
                ("creation_date", models.DateTimeField(auto_created=True, blank=True)),
                ("text", models.CharField(max_length=280)),
                (
                    "status",
                    models.CharField(
                        choices=[("DRF", "Draft"), ("PUB", "Published")],
                        default="DRF",
                        max_length=3,
                    ),
                ),
                ("is_private", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-creation_date",),
            },
        ),
    ]
