# Generated by Django 4.2 on 2023-04-19 12:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="creation_date",
            field=models.DateTimeField(auto_created=True, blank=True),
        ),
        migrations.AlterField(
            model_name="article",
            name="last_modification_date",
            field=models.DateTimeField(auto_created=True, blank=True),
        ),
    ]
